import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import { Inter } from "next/font/google"
import {Toaster} from "react-hot-toast"

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700'], })

export const metadata: Metadata = {
  title: "QuizMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        <Provider>
          <Toaster 
          position="top-center"
          reverseOrder= {false}
          />
          {children}
        </Provider>
      </body>
    </html>
  );
}
